#!/usr/bin/env bash
#
# bootstrap installs things.



cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

source $DOTFILES_ROOT/bin/link-file

set -e

install_dotfiles () {
  info 'Installing dotfiles'

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

install_vs_settings () {
  info 'Copying VSCode Settings'

  local overwrite_all=false backup_all=false skip_all=false

  mkdir -p "$HOME/Library/Application Support/Code/User/"
  link_file "$DOTFILES_ROOT/vscode/settings.json" "$HOME/Library/Application Support/Code/User/settings.json"
}

echo ''
echo 'Updating Dotfiles'
install_dotfiles

echo ''
echo 'Updating VSCode Settings'
install_vs_settings

echo ''
echo 'Finding the installers and running them iteratively'
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done

echo ''
echo "Set macOS defaults"
$DOTFILES_ROOT/macos/set-defaults.sh