# Display time
SPACESHIP_TIME_SHOW=true

# Git
SPACESHIP_GIT_SHOW=true
SPACESHIP_GIT_BRANCH_SHOW=true
SPACESHIP_GIT_STATUS_SHOW=true

# Do not truncate path in repos
SPACESHIP_DIR_TRUNC_REPO=false

SPACESHIP_RUBY_SHOW=true

SPACESHIP_XCODE_SHOW_LOCAL=true